name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          #curl -fsSL https://ollama.com/install.sh | sh
          brew install ollama
          brew services start ollama
          sleep 10
          sh batch.sh llama3
