name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          #curl -fsSL https://ollama.com/install.sh | sh
          brew install ollama
          brew services start ollama
          sleep 10
          cat models.txt | ggrep -v # | xargs -I{} sh -x batch.sh {}
