on:
  push:
    branches: [ main ]
  #schedule:
    #- cron: '0 * * * *'
jobs:
  build:
    runs-on: macos-latest
    #runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          export LANG=ja_JP.UTF-8
          export LC_ALL=ja_JP.UTF-8
          echo "LANG=ja_JP.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=ja_JP.UTF-8" >> $GITHUB_ENV
          LANG=ja_JP.UTF-8
          LC_ALL=ja_JP.UTF-8
          #brew install go
          #git clone https://github.com/ollama/ollama.git
          #cd ollama
          #make
          #curl -fsSL https://ollama.com/install.sh | sh &> /dev/null
          #./ollama serve &
          brew install ollama
          brew services start ollama
          sleep 10
          cat models.txt | grep -v "#" | xargs -I{} sh batch.sh {}
          #sort -R | 
